import ray
import os
# import time
import json
from verifier import run_verification

# Suppress Ray's future warning regarding GPU masking
os.environ["RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO"] = "0"

def initialize_dispatcher():
    num_cores = os.cpu_count()
    if not ray.is_initialized():
        ray.init(num_cpus=num_cores, log_to_driver=False)
    print(f"[SYSTEM] Ray cluster active. Cores available: {num_cores}\n")
    return num_cores

# The parallel worker now executes the actual Verification Wrapper
@ray.remote(num_cpus=1)
def verify_design_worker(workspace_dir: str, module_name: str):
    return run_verification(workspace_dir, module_name)
# def mock_eda_worker(task_id: int, variation_name: str):
#     print(f"--> [Worker {task_id}] Started compiling: {variation_name}")
#     time.sleep(3) 
#     print(f"<-- [Worker {task_id}] Finished: {variation_name}")
#     return {"task_id": task_id, "status": "SUCCESS", "variation": variation_name}

if __name__ == "__main__":
    initialize_dispatcher()
    
    # 1. Look at the isolated workspaces generated by Week 2
    workspace_base = "workspace"
    if not os.path.exists(workspace_base):
        print("❌ ERROR: No workspace found. Run llm_client.py from Week 2 first.")
        exit(1)
        
    run_folders = [os.path.join(workspace_base, d) for d in os.listdir(workspace_base) if d.startswith("run_")]
    
    # We assume the module name generated by the JSON spec was 'alu'
    module_name = "alu_4bit"
    
    print(f"[RACE STARTED] Dispatching {len(run_folders)} Verilog architectures for parallel verification...")
    
    # 2. Dispatch all folders to the Ray Cluster simultaneously
    futures = [verify_design_worker.remote(folder, module_name) for folder in run_folders]
    
    # 3. Block and wait for all Verilator C++ compilations to finish
    results = ray.get(futures)
    
    # 4. The Winner Selection Logic
    passed_designs = [res for res in results if res["status"] == "PASS"]
    
    print("\n================ VERIFICATION RESULTS ================")
    for res in results:
        icon = "✅" if res["status"] == "PASS" else "❌"
        print(f"{icon} {res['workspace']} | Time: {res['execution_time']:.2f}s")
        
        # If it failed, print a snippet of the error for context
        if res["status"] == "FAIL":
            print(f"    -> Error Snippet: {res['log'].splitlines()[-3:]}")

    print("\n================ WINNER SELECTION ================")
    if passed_designs:
        # Sort the passed designs by execution time (fastest compilation/simulation wins)
        winner = sorted(passed_designs, key=lambda x: x["execution_time"])[0]
        print(f"🏆 WINNER DECLARED: {winner['workspace']}")
        print(f"🏆 METRIC: Passed Verilator/Cocotb tests in {winner['execution_time']:.2f} seconds.")
        print(f"🏆 NEXT STEP: Passing {winner['workspace']}/design.sv to Digital Back-End (Yosys).")
    else:
        print("💀 ALL DESIGNS FAILED. Initiating LLM Critic Agent loop (To be built in Optimization Phase).")
    #print("[SYSTEM] Dispatcher module loaded. Run this via the main CLI.")
    
    # cores = initialize_dispatcher()
    # designs = ["Ripple-Carry", "Carry-Lookahead", "Kogge-Stone", "Brent-Kung", "Sklansky"]
    
    # print(f"Dispatching {len(designs)} tasks to {cores} available cores...")
    # start_time = time.time()
    
    # futures = [mock_eda_worker.remote(i, design) for i, design in enumerate(designs)]
    # results = ray.get(futures)
    
    # end_time = time.time()
    
    # print("\n[RESULTS] All tasks completed:")
    # for res in results:
    #     print(res)
        
    # print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")
# #V1:
# import ray
# import os
# import time

# def initialize_dispatcher():
#     # Detect available CPU cores in the Codespace
#     num_cores = os.cpu_count()
#     print(f"[SYSTEM] Detected {num_cores} CPU cores.")

#     # Initialize Ray, restricting it to available cores so it doesn't crash the VM
#     if not ray.is_initialized():
#         ray.init(num_cpus=num_cores, log_to_driver=False)
#     print("[SYSTEM] Ray cluster initialized successfully.\n")
#     return num_cores

# # The @ray.remote decorator converts this function into an asynchronous worker task.
# # We specify num_cpus=1 to tell Ray each task consumes exactly 1 CPU core.
# @ray.remote(num_cpus=1)
# def mock_eda_worker(task_id: int, variation_name: str):
#     print(f"--> [Worker {task_id}] Started compiling: {variation_name}")
    
#     # Simulate a heavy CPU-bound task (like Verilator compiling RTL)
#     time.sleep(3) 
    
#     print(f"<-- [Worker {task_id}] Finished: {variation_name}")
#     return {"task_id": task_id, "status": "SUCCESS", "variation": variation_name}

# if __name__ == "__main__":
#     cores = initialize_dispatcher()
    
#     # Define 5 mock Verilog architectural variations (Week 2 preview)
#     designs = ["Ripple-Carry", "Carry-Lookahead", "Kogge-Stone", "Brent-Kung", "Sklansky"]
    
#     print(f"Dispatching {len(designs)} tasks to {cores} available cores...")
#     start_time = time.time()

#     # Dispatch the tasks asynchronously. This creates a list of "ObjectRefs" (futures).
#     futures = [mock_eda_worker.remote(i, design) for i, design in enumerate(designs)]

#     # ray.get() acts as a barrier, blocking execution until ALL workers finish.
#     results = ray.get(futures)

#     end_time = time.time()
    
#     print("\n[RESULTS] All tasks completed:")
#     for res in results:
#         print(res)
        
#     print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")