import ray
import os
import time
import json
from verifier import run_verification
from synthesizer import run_synthesis
from openlane_wrapper import run_openlane

# Suppress Ray's future warning regarding GPU masking
os.environ["RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO"] = "0"

def initialize_dispatcher():
    num_cores = os.cpu_count()
    if not ray.is_initialized():
        ray.init(num_cpus=num_cores, log_to_driver=False)
    print(f"[SYSTEM] Ray cluster active. Cores available: {num_cores}\n")
    return num_cores

# The parallel worker now executes the actual Verification Wrapper
@ray.remote(num_cpus=1)
def verify_design_worker(workspace_dir: str, module_name: str):
    return run_verification(workspace_dir, module_name)

if __name__ == "__main__":
    from llm_client import EDA_LLM_Client

    initialize_dispatcher()
    ai_client = EDA_LLM_Client()

    MAX_RETRIES = 3

    # 1. Look at the isolated workspaces generated by Week 2
    workspace_base = "workspace"
    if not os.path.exists(workspace_base):
        print("❌ ERROR: No workspace found. Run llm_client.py from Week 2 first.")
        exit(1)

    run_folders = [os.path.join(workspace_base, d) for d in os.listdir(workspace_base) if d.startswith("run_")]

    # We assume the module name generated by the JSON spec was 'alu'
    module_name = "alu_4bit"
    winner = None

    for attempt in range(MAX_RETRIES):
        print(f"\n================ ATTEMPT {attempt + 1}/{MAX_RETRIES} ================")
        print(f"[RACE STARTED] Dispatching {len(run_folders)} Verilog architectures for parallel verification...")

        # 2. Dispatch all folders to the Ray Cluster simultaneously
        futures = [verify_design_worker.remote(folder, module_name) for folder in run_folders]

        # 3. Block and wait for all compilations to finish
        results = ray.get(futures)

        # 4. The Winner Selection Logic
        passed_designs = [res for res in results if res["status"] == "PASS"]

        print("\n================ VERIFICATION RESULTS ================")
        for res in results:
            icon = "✅" if res["status"] == "PASS" else "❌"
            print(f"{icon} {res['workspace']} | Time: {res['execution_time']:.2f}s")

            if res["status"] == "FAIL":
                print(f"    -> Error Snippet: {res['log'].splitlines()[-3:]}")

        print("\n================ WINNER SELECTION ================")
        if passed_designs:
            winner = sorted(passed_designs, key=lambda x: x["execution_time"])[0]
            print(f"🏆 WINNER DECLARED: {winner['workspace']}")
            print(f"🏆 METRIC: Passed Verilator/Cocotb tests in {winner['execution_time']:.2f} seconds.")
            break  # Exit the retry loop on success

        # --- SELF-HEALING CRITIC LOOP ---
        print("💀 ALL DESIGNS FAILED this round.")

        if attempt < MAX_RETRIES - 1:
            # a. Pick the fastest failure as the best candidate for repair
            best_failure = sorted(results, key=lambda x: x["execution_time"])[0]
            print(f"\n[CRITIC AGENT] Selecting fastest failure for repair: {best_failure['workspace']}")

            # b. Read the broken code
            broken_path = os.path.join(best_failure["workspace"], "design.sv")
            with open(broken_path, "r") as f:
                broken_code = f.read()

            # Read the testbench so the critic knows the interface contract
            testbench_path = os.path.join(best_failure["workspace"], "test_alu.py")
            with open(testbench_path, "r") as f:
                testbench_code = f.read()

            # c. Ask the LLM to fix it
            print(f"[CRITIC AGENT] Attempting Fix (Retry {attempt + 2}/{MAX_RETRIES})...")
            fixed_code = ai_client.fix_design(broken_code, best_failure["log"])

            # Debug: see exactly what the LLM produced
            print(f"[DEBUG] ===== FIXED design.sv =====")
            print(fixed_code[:500])  # First 500 chars is enough
            print(f"[DEBUG] ===== END FIXED CODE =====")

            # d. Overwrite design.sv in ALL workspace folders with the corrected code
            for folder in run_folders:
                target_file = os.path.join(folder, "design.sv")
                with open(target_file, "w") as f:
                    f.write(fixed_code)
                print(f"  -> Patched: {target_file}")

            print("[CRITIC AGENT] All workspaces patched. Re-racing...\n")
        else:
            print("💀 ALL RETRIES EXHAUSTED. No design passed verification.")

    # --- POST-LOOP: PROCEED ONLY IF WE HAVE A WINNER ---
    if winner:
        print(f"\n================ DIGITAL BACK-END (DBE) ================")
        print(f"Passing {winner['workspace']}/design.sv to Yosys for synthesis...")

        synth_metrics = run_synthesis(winner["workspace"], winner["module_name"])

        if synth_metrics["status"] == "PASS":
            print("✅ SYNTHESIS SUCCESS!")
            print(f"📊 HARDWARE COST (AREA): {synth_metrics['gate_count']} Logic Gates")
            print(f"⏱️  SYNTHESIS TIME: {synth_metrics['execution_time']:.2f} seconds")

            # --- TRIGGER OPENLANE PHYSICAL DESIGN ---
            run_openlane(winner["workspace"], winner["module_name"])
        else:
            print("❌ SYNTHESIS FAILED!")
            print(f"Error Snippet: {synth_metrics['log_snippet']}")
    else:
        print("\n🛑 ABORTING: No valid design produced after all retries. Pipeline halted.")
        exit(1)

# def mock_eda_worker(task_id: int, variation_name: str):
#     print(f"--> [Worker {task_id}] Started compiling: {variation_name}")
#     time.sleep(3) 
#     print(f"<-- [Worker {task_id}] Finished: {variation_name}")
#     return {"task_id": task_id, "status": "SUCCESS", "variation": variation_name}

# if __name__ == "__main__":
#     initialize_dispatcher()
    
#     # 1. Look at the isolated workspaces generated by Week 2
#     workspace_base = "workspace"
#     if not os.path.exists(workspace_base):
#         print("❌ ERROR: No workspace found. Run llm_client.py from Week 2 first.")
#         exit(1)
        
#     run_folders = [os.path.join(workspace_base, d) for d in os.listdir(workspace_base) if d.startswith("run_")]
    
#     # We assume the module name generated by the JSON spec was 'alu'
#     module_name = "alu_4bit"
    
#     print(f"[RACE STARTED] Dispatching {len(run_folders)} Verilog architectures for parallel verification...")
    
#     # 2. Dispatch all folders to the Ray Cluster simultaneously
#     futures = [verify_design_worker.remote(folder, module_name) for folder in run_folders]
    
#     # 3. Block and wait for all Verilator C++ compilations to finish
#     results = ray.get(futures)
    
#     # 4. The Winner Selection Logic
#     passed_designs = [res for res in results if res["status"] == "PASS"]
    
#     print("\n================ VERIFICATION RESULTS ================")
#     for res in results:
#         icon = "✅" if res["status"] == "PASS" else "❌"
#         print(f"{icon} {res['workspace']} | Time: {res['execution_time']:.2f}s")
        
#         # If it failed, print a snippet of the error for context
#         if res["status"] == "FAIL":
#             print(f"    -> Error Snippet: {res['log'].splitlines()[-3:]}")

#     print("\n================ WINNER SELECTION ================")
#     if passed_designs:
#         # Sort the passed designs by execution time
#         winner = sorted(passed_designs, key=lambda x: x["execution_time"])[0]
#         print(f"🏆 WINNER DECLARED: {winner['workspace']}")
#         print(f"🏆 METRIC: Passed Verilator/Cocotb tests in {winner['execution_time']:.2f} seconds.")
        
#         # --- WEEK 4: DIGITAL BACK-END TRIGGER ---
#         print(f"\n================ DIGITAL BACK-END (DBE) ================")
#         print(f"Passing {winner['workspace']}/design.sv to Yosys for synthesis...")
        
#         synth_metrics = run_synthesis(winner['workspace'], ['module_name'])
        
#         if synth_metrics["status"] == "PASS":
#             print("✅ SYNTHESIS SUCCESS!")
#             print(f"📊 HARDWARE COST (AREA): {synth_metrics['gate_count']} Logic Gates")
#             print(f"⏱️  SYNTHESIS TIME: {synth_metrics['execution_time']:.2f} seconds")
            
#             # --- TRIGGER OPENLANE PHYSICAL DESIGN ---
#             run_openlane(winner['workspace'], winner['module_name'])

#         else:
#             print("❌ SYNTHESIS FAILED!")
#             print(f"Error Snippet: {synth_metrics['log_snippet']}")

#     else:
#         print("💀 ALL DESIGNS FAILED. Initiating LLM Critic Agent loop (To be built in Optimization Phase).")
    # print("\n================ WINNER SELECTION ================")
    # if passed_designs:
    #     # Sort the passed designs by execution time (fastest compilation/simulation wins)
    #     winner = sorted(passed_designs, key=lambda x: x["execution_time"])[0]
    #     print(f"🏆 WINNER DECLARED: {winner['workspace']}")
    #     print(f"🏆 METRIC: Passed Verilator/Cocotb tests in {winner['execution_time']:.2f} seconds.")
    #     print(f"🏆 NEXT STEP: Passing {winner['workspace']}/design.sv to Digital Back-End (Yosys).")
    # else:
    #     print("💀 ALL DESIGNS FAILED. Initiating LLM Critic Agent loop (To be built in Optimization Phase).")
    #print("[SYSTEM] Dispatcher module loaded. Run this via the main CLI.")
    
    # cores = initialize_dispatcher()
    # designs = ["Ripple-Carry", "Carry-Lookahead", "Kogge-Stone", "Brent-Kung", "Sklansky"]
    
    # print(f"Dispatching {len(designs)} tasks to {cores} available cores...")
    # start_time = time.time()
    
    # futures = [mock_eda_worker.remote(i, design) for i, design in enumerate(designs)]
    # results = ray.get(futures)
    
    # end_time = time.time()
    
    # print("\n[RESULTS] All tasks completed:")
    # for res in results:
    #     print(res)
        
    # print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")
# #V1:
# import ray
# import os
# import time

# def initialize_dispatcher():
#     # Detect available CPU cores in the Codespace
#     num_cores = os.cpu_count()
#     print(f"[SYSTEM] Detected {num_cores} CPU cores.")

#     # Initialize Ray, restricting it to available cores so it doesn't crash the VM
#     if not ray.is_initialized():
#         ray.init(num_cpus=num_cores, log_to_driver=False)
#     print("[SYSTEM] Ray cluster initialized successfully.\n")
#     return num_cores

# # The @ray.remote decorator converts this function into an asynchronous worker task.
# # We specify num_cpus=1 to tell Ray each task consumes exactly 1 CPU core.
# @ray.remote(num_cpus=1)
# def mock_eda_worker(task_id: int, variation_name: str):
#     print(f"--> [Worker {task_id}] Started compiling: {variation_name}")
    
#     # Simulate a heavy CPU-bound task (like Verilator compiling RTL)
#     time.sleep(3) 
    
#     print(f"<-- [Worker {task_id}] Finished: {variation_name}")
#     return {"task_id": task_id, "status": "SUCCESS", "variation": variation_name}

# if __name__ == "__main__":
#     cores = initialize_dispatcher()
    
#     # Define 5 mock Verilog architectural variations (Week 2 preview)
#     designs = ["Ripple-Carry", "Carry-Lookahead", "Kogge-Stone", "Brent-Kung", "Sklansky"]
    
#     print(f"Dispatching {len(designs)} tasks to {cores} available cores...")
#     start_time = time.time()

#     # Dispatch the tasks asynchronously. This creates a list of "ObjectRefs" (futures).
#     futures = [mock_eda_worker.remote(i, design) for i, design in enumerate(designs)]

#     # ray.get() acts as a barrier, blocking execution until ALL workers finish.
#     results = ray.get(futures)

#     end_time = time.time()
    
#     print("\n[RESULTS] All tasks completed:")
#     for res in results:
#         print(res)
        
#     print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")