import cocotb
from cocotb.triggers import Timer, ReadOnly
import json
import os
import sys
from pathlib import Path

# Add current directory to path so we can import the dynamically generated files
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# ==============================================================================
# MATH EQUIVALENCE CHECKS (Generated by AI Planner)
# ==============================================================================
from golden_model import golden_model, generate_test_vectors

if os.environ.get("SIM", "verilator") == "verilator":
    os.environ["COCOTB_TRACING"] = "1"

@cocotb.test()
async def branch_comparator_math_equivalence(dut):
    """Compares DUT datapath arithmetic outputs against the Python golden model."""
    model_state = {}
    try:
        test_vectors = generate_test_vectors()
        if not test_vectors:
            raise ValueError("generate_test_vectors returned None or empty")
    except Exception as exc:
        assert False, f"Golden model vector generation failed: {exc}"

    for i, input_dict in enumerate(test_vectors):
        for port_name, val in input_dict.items():
            if hasattr(dut, port_name):
                getattr(dut, port_name).value = int(val)
        await Timer(1, unit="ns")
        await ReadOnly()

        hardware_result = {}
        
        try:
            hardware_result["branch_taken"] = int(dut.branch_taken.value)
        except ValueError:
            hardware_result["branch_taken"] = 0
        
        try:
            hardware_result["eq_flag"] = int(dut.eq_flag.value)
        except ValueError:
            hardware_result["eq_flag"] = 0
        
        try:
            hardware_result["lt_signed"] = int(dut.lt_signed.value)
        except ValueError:
            hardware_result["lt_signed"] = 0
        
        try:
            hardware_result["lt_unsigned"] = int(dut.lt_unsigned.value)
        except ValueError:
            hardware_result["lt_unsigned"] = 0
        

        try:
            _, expected_output = golden_model(model_state, input_dict)
        except Exception as exc:
            assert False, f"Golden model failed on iteration {i}: {exc}"

        assert hardware_result == expected_output, \
            f"Math equivalence failure: Inputs={input_dict} | HW={hardware_result} | GOLDEN={expected_output}"
    dut._log.info("✅ Math equivalence checks passed for all golden vectors.")